name = "resume-api"
main = "src/index.ts"
compatibility_date = "2026-03-27"
workers_dev = true

[vars]
CORS_ORIGINS = "http://10.140.58.27,http://127.0.0.1:8787,https://haolun-wang.pages.dev,https://resume-api-haolun-wang.9b117201.workers.dev"
GOOGLE_OAUTH_SCOPES = "openid email profile"


[[d1_databases]]
binding = "DB"
database_name = "resume-api-db"
database_id = "41be8a01-6d89-4bb8-8dea-84bc002a1175"