name = "resume-api-haolun-wang"
main = "src/index.ts"
compatibility_date = "2026-03-27"
workers_dev = true

[vars]
CORS_ORIGINS = "http://localhost:4200,https://haolun-wang.pages.dev"

[[d1_databases]]
binding = "DB"
database_name = "resume-api-db"
database_id = "41be8a01-6d89-4bb8-8dea-84bc002a1175"
